cryoAsicGen1:
  enable: True
  ForceWrite: False
  InitAfterConfig: False
  PollEn: True
  dataWriter:
    enable: True
    DataFile: ''
    IsOpen: False
    BufferSize: 0
    MaxFileSize: 0
  EpixHRGen1Cryo:
    enable: True
    MMCMSerdesRegisters:
      enable: True
      CLKOUT0PhaseMux: 0
      CLKOUT0HighTime: 2
      CLKOUT0LowTime: 2
      CLKOUT0Frac: 0
      CLKOUT0FracEn: 0
      CLKOUT0Edge: 0
      CLKOUT0NoCount: 0
      CLKOUT0DelayTime: 0
      CLKOUT1PhaseMux: 0
      CLKOUT1HighTime: 8
      CLKOUT1LowTime: 8
      CLKOUT1Edge: 0
      CLKOUT1NoCount: 0
      CLKOUT1DelayTime: 0
      CLKOUT2PhaseMux: 0
      CLKOUT2HighTime: 14
      CLKOUT2LowTime: 14
      CLKOUT2Edge: 0
      CLKOUT2NoCount: 0
      CLKOUT2DelayTime: 0
      CLKOUT3PhaseMux: 0
      CLKOUT3HighTime: 2
      CLKOUT3LowTime: 2
      CLKOUT3Edge: 0
      CLKOUT3NoCount: 0
      CLKOUT3DelayTime: 0
