cryoAsicGen1:
  enable: True
  ForceWrite: False
  KCU105FEMBCryo:
    enable: True
    CryoAsic1:
      enable: True
      RowStart: 0xff
      RowStop: 0x2f
      ColStart: 0xff
      StartPixel: 0x0
      bleak_boost: 0x0
      TPS_DAC: 0x3c
      TPS_GR: 0x1
      TPSMux: 0x0
      Bias_TPS_Buffer: 0x5
      Bias_TPS: 0x4
      Bias_TPS_DAC: 0x4
      Bias_LVDS_Rx: 0x0
      Bias_LVDS_Tx: 0x0
      RbiasEn: False
      Pulser: 0x370
      test: True
      atest: False
      hrtest: False
      sbatest: False
      pbit: False
      Pulser_Reset: False
      PPbit: True
      test_BE: False
      DelEXEC: False
      DelCCKreg: False
      sync_exten: False
      sync_role_sel: True
      RO_Bk0_disable: False
      RO_Bk1_disable: False
      DM1en: False
      DM2en: False
      Pulser_Monost: 0x0
      cs_LVDS_Tx: 0x0
      DCycle_en: False
      DCycle_bypass: False
      DCycle_polarity: False
      DCycle_DAC: 0x20
      Bias_DCycle_DAC: 0x4
      PLL_RO_OutDivider: 0x0
      PLL_DCycle_Bypass_B0: 0x3
      PLL_RO_Reset: True
      PLL_RO_Itune: 0x3
      PLL_RO_KVCO: 0x1
      PLL_RO_filter1: 0x5
      PLL_RO_filter2: 0x4
      Dcycle_DAC_gain: 0x3
      VTBias_B0: 0x2
      VTBias_T0: 0xe
      SAH_B0: 0x0
      SAH_VcmBuf_B0: 0x0
      SigBuf_B0: 0x0
      ADC_VrefBuf_B0: 0x0
      ADC_B0: 0x3
      ADC_VcmBuf_B0: 0x0
      bamp: 0x4
      bleak: 0x2
      brstVref: 0x4
      SAH_Ctrl_Visel: False
      ADC_Ocen_Bk0: True
      ADC_Ocen_Bk1: True
      VrefBuffExt_En_Bk0: True
      VrefBuffExt_En_Bk1: True
      ROsLVDS_bit: True
      SACIsLVDS_bit: True
      d_emph: 0x0
      pre_emph_en: False
      PLL_RO_Itune_b3: 0x0
      PLL_RO_KVCO_b3: 0x0
      DM1sel: 0x0
      DM2sel: 0x0
      SubBnkEn: 0xFFFF
      LDO_VTBias_B0: 0x3
      LDO_VTBias_T0: 0xc
      LDO_VTBias_Br0: 0x0
      LDO_VTBias_Tr0: 0x0
      TPS_DAC_Gain: 0x3
      S2D_MX: False
      LDO0TB_En: True
      LDO0rTB_En: True
      LDO1TB_En: True
      LDO2TB_En: True
      LDO46_En: True
      encoder_mode_dft: 0x0
      En_BankClk_Bk0_LVDS: False
      En_BankClk_Bk1_LVDS: False
      En_SerClk_out_Bk0_LVDS: True
      En_SerClk_out_Bk1_LVDS: True
      rtrimLVDS_b0: 0x2
      SACItristateLVDS_bit: False
      VrefGen_B0_1v2: 0x3
      VrefGen_Br0_1v2: 0x3
      VrefGen_T0_1v2: 0xf
      VrefGen_Tc0_1v2: 0xf
      VrefGen_Tr0_1v2: 0x0
      VrefBuf_Ext_B0_1v2: 0x3
      VcmBuf_Ext_B0_1v2: 0x0
      FE_Amp_B0_1v2: 0x2
      bifb: 0x3
      bbaseref: 0x3
      blcoarse: 0x3
      ctrl_pulser: False
      Pulser_Bias_DAC_b0: 0x4
      PP_Pulser_Bias_DAC: True
      Pulser_Bias_Monost_b0: 0x3
      ensdps: False
      enrefps: False
      Ana_Mon_Cal: False
      ADC_B3B2: 0x2
      eFuse_ADDR: 0x0
      eFuse_Q: 0x7251
      LDO1V_VTBias_B: 0x3
      LDO1V_VTBias_T: 0x9
      LDO1V_VTBias_Br: 0x0
      LDO1V_VTBias_Tr: 0x9
      Rate_mode_b: 0x0
      PLL_div_sel: 0x0
    AppFpgaRegisters:
      enable: True
      Version: 0x2
      GlblRstPolarity: True
      GlblRstDelay: 0
      GlblRstWidth: 0
      AcqPolarity: False
      AcqDelay1: 1000
      AcqWidth1: 100000
      AcqDelay2: 0
      AcqWidth2: 0
      TPulsePolarity: False
      TPulseDelay: 0
      TPulseWidth: 0
      StartPolarity: False
      StartDelay: 0
      StartWidth: 0
      PPbePolarity: False
      PPbeDelay: 0
      PPbeWidth: 0
      SampClkEn: False
      SyncPolarity: True
      SyncDelay: 0
      SyncWidth: 0
      SaciSyncPolarity: False
      SaciSyncDelay: 0
      SaciSyncWidth: 0
      SR0Polarity: False
      Vid: 0
      ResetCounters: False
      AsicPwrEnable: True
      AsicPwrManual: False
      AsicPwrManualDig: False
      AsicPwrManualAna: False
      AsicPwrManualIo: False
      AsicPwrManualFpga: False
      DebugSel1: 9
      DebugSel2: 3
      StartupReq: True
