cryoAsicGen1:
  enable: True
  KCU105FEMBCryo:
    enable: True
    MMCMSerdesRegisters:
      enable: True
      CLKOUT0PhaseMux: 0
      CLKOUT0HighTime: 1
      CLKOUT0LowTime: 1
      CLKOUT0Frac: 0
      CLKOUT0FracEn: 0
      CLKOUT0Edge: 0
      CLKOUT0NoCount: 0
      CLKOUT0DelayTime: 0
      CLKOUT1PhaseMux: 0
      CLKOUT1HighTime: 4
      CLKOUT1LowTime: 4
      CLKOUT1Edge: 0
      CLKOUT1NoCount: 0
      CLKOUT1DelayTime: 0
      CLKOUT2PhaseMux: 0
      CLKOUT2HighTime: 7
      CLKOUT2LowTime: 7
      CLKOUT2Edge: 0
      CLKOUT2NoCount: 0
      CLKOUT2DelayTime: 0
      CLKOUT3PhaseMux: 0
      CLKOUT3HighTime: 8
      CLKOUT3LowTime: 8
      CLKOUT3Edge: 0
      CLKOUT3NoCount: 0
      CLKOUT3DelayTime: 0
